# Generated by Django 5.1.1 on 2024-09-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author_name",
            field=models.CharField(default="hagp", max_length=255),
            preserve_default=False,
        ),
    ]
