# Generated by Django 5.1.1 on 2024-09-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_book_readers_alter_book_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookrelation",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Ok"),
                    (2, "Fine"),
                    (3, "Good"),
                    (4, "Great"),
                    (5, "Awesome"),
                ],
                null=True,
            ),
        ),
    ]
